export type Severity = "critical" | "high" | "medium" | "low";
export type FindingStatus = "open" | "accepted" | "rejected";
export interface Reference { title: string; kind: string; score: number; text: string }
export interface Finding { id: string; n?: number; severity: Severity; category: string; title: string; detail: string; confidence: number; loc?: number[] | null; rule?: string; status: FindingStatus; note?: string; page?: number; references?: Reference[]; voice_notes?: { file: string; transcript?: string }[] }
export interface TitleField { value: string; conf: number; source?: string }
export interface Region { cls: string; bbox: number[]; conf: number }
export interface Extraction { source: { kind: string; units?: string; dxfversion?: string; scale?: number | null; raster?: boolean; pages?: number; ocr?: string; layout_model?: string; regions?: Region[][]; page_sizes?: number[][] }; texts?: { text: string; bbox?: number[]; kind?: string; conf?: number; page?: number }[]; counts: { texts: number; dimensions: number; circles: number; fcfs: number; notes: number }; title_block: { fields: Record<string, TitleField> }; notes: { n: number; text: string }[]; dimensions: { type: string; text: string; measured?: number | null; override?: boolean; tol?: unknown }[]; fcfs: { symbol?: string; tolerance?: number; diameter?: boolean; modifiers?: string[]; datums?: string[] }[]; datums: { id: string }[]; threads: { spec: string; tap_drill?: number; circle?: { r: number; via: string } | null }[]; callouts: { text: string }[]; specs: { ref: string; rev?: string | null }[]; parts_list?: { rows: { item: string; qty: string; part_no: string; description?: string; rev?: string }[] } | null; warnings?: string[]; circles?: unknown[]; space?: string }
export interface Drawing { id: string; file: string; kind: string; part_no?: string | null; rev?: string | null; title?: string | null; extraction?: Extraction | null; findings: Finding[]; checked_at?: string | null; duration?: number | null; error?: string | null; pages: number; status?: string; trace?: { node: string; status: string; ms: number; detail: string }[] }
export interface DrawingSummary { id: string; file: string; kind: string; part_no?: string | null; rev?: string | null; title?: string | null; findings: number; open: number; worst?: Severity | null; checked_at?: string | null; duration?: number | null; error?: string | null; status?: string }
export interface JobSummary { id: string; name: string; created: string; customer: string; drawings: DrawingSummary[]; has_step: boolean; has_bom: boolean; has_po: boolean; status?: string }
export interface Job { id: string; name: string; customer: string; created: string; drawings: Drawing[]; files: Record<string, unknown>; status?: string; consistency?: ConsistencyReport | null; model_check?: ModelReport | null }
export interface Status { version: string; claude: boolean; model: string; jobs: number; templates: number; engines?: { orchestration: string; retrieval: { embeddings?: string; store?: string; documents?: number; error?: string }; queue: { async: boolean; broker: boolean; workers: boolean }; step: string; ocr?: string | null; layout_model: string; plm: string; storage: string; voice_notes: boolean; illustrations: string } }
export interface CompareChange { kind: string; item: string; a: string; b: string; change: string; impact: string; why: string }
export interface CompareReport { labelA: string; labelB: string; summary: { total: number; dimensions: number; notes: number; callouts: number; title_block: number; gdt: number; affects_fit: number; process: number }; changes: CompareChange[]; eco: { part_no: string; rev: string; drawing_eco?: string | null; plm_eco?: string | null; plm_rev?: string | null; released?: string | null; status: string; source?: string }; downstream: string[] }
export interface ConsistencyRow { field: string; part: string; drawing: string; bom: string; po: string; status: string; label: string; detail: string }
export interface ConsistencyReport { rows: ConsistencyRow[]; conflicts: number; sources: string[]; errors?: string[] }
export interface ModelRow { feature: string; drawing: string; model: string; status: string; detail?: string }
export interface ModelReport { error?: string; model?: { file?: string; product?: string | null; units?: string; cylinders?: { diameter: number; surfaces: number }[]; extents?: { x: number; y: number; z?: number | null } | null; schema?: string | null; engine?: string }; drawings: { file: string; rows: ModelRow[]; matches: number; conflicts: number; skipped?: string }[] }
export interface Template { name: string; kind: string; size: number; description: string }
export interface BulkResult { find: string; replace: string; total: number; preview: boolean; results: { file: string; kind: string; count: number; mode: string; previews: { before: string; after: string; cell?: string }[] }[]; files: { name: string; url: string }[] }
export interface Answer { answer: string; citations: string[]; mode: string; model?: string; tools_used?: string[] }
export interface AuditRow { time: string; event: string; [k: string]: unknown }
export interface MeshFace { kind: string; diameter: number | null; status: "match" | "conflict" | "info" | "neutral"; tris: number[][] }
export interface Mesh { vertices: number[][]; faces: MeshFace[]; bbox: number[][]; triangles: number; drawing?: string | null; product?: string | null; legend: { diameter: number; status: string }[]; engine?: string }
export interface DocResult { name: string; url: string; rows?: number; images?: number; characteristics?: { n: number; characteristic: string; nominal: string; tol: string; method: string; freq: string }[] }

export interface CustomerSummary { slug: string; name: string; has_setup: boolean; jobs: number; drawings: number; missing: Record<string, number>; updated?: string | null }
export interface CustomerField { field: string; label: string; standard_labels: string[]; standard_tags: string[]; labels: string[]; tags: string[]; required: boolean; severity: Severity }
export interface Suggestion { kind: "label" | "tag"; text: string; example?: string | null; field?: string | null; drawings: number; files: string[] }
export interface Customer { slug: string; name: string; has_setup: boolean; updated?: string | null; fields: CustomerField[]; jobs: { id: string; name: string; drawings: number }[]; missing: Record<string, number>; suggestions: Suggestion[] }
export interface SpecRecord { ref: string; title?: string; revisions: string[]; current?: string | null; superseded?: Record<string, string>; on_file?: boolean }
export interface RevisionRecord { part_no: string; rev: string; eco?: string; released?: string; title?: string; history?: { rev: string; eco?: string; released?: string }[] }
export interface ImportResult { imported: number; errors: string[]; total: number; specs?: string[]; parts?: string[] }
